2025-06-27T11:50:02: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T11:50:02: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T11:56:40: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T11:56:40: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T11:56:50: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:09:19: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:09:19: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:09:28: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.180.228:27017, connect ENETUNREACH 64:ff9b::9f29:b4e4:27017 - Local (:::0)
2025-06-27T12:09:29: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:09:29: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:09:39: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:09:46: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.180.228:27017, connect ENETUNREACH 64:ff9b::9f29:b4e4:27017 - Local (:::0)
2025-06-27T12:09:47: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:09:47: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:09:58: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:10:01: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:10:01: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:10:09: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.180.228:27017, connect ENETUNREACH 64:ff9b::9f29:b4e4:27017 - Local (:::0)
2025-06-27T12:10:11: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:10:12: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:10:22: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:10:32: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.180.228:27017, connect ENETUNREACH 64:ff9b::9f29:b4e4:27017 - Local (:::0)
2025-06-27T12:10:34: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:10:34: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:10:46: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:11:02: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:11:02: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:11:04: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.180.228:27017, connect ENETUNREACH 64:ff9b::9f29:b4e4:27017 - Local (:::0)
2025-06-27T12:11:05: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:11:06: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:11:16: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:11:54: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:11:54: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:12:05: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:12:25: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:12:26: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:12:36: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:13:18: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:13:18: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:13:29: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:13:49: Error connecting to MongoDB Atlas: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
2025-06-27T12:14:04: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:14:05: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:14:11: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.180.228:27017, connect ENETUNREACH 64:ff9b::9f29:b4e4:27017 - Local (:::0)
2025-06-27T12:14:13: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:14:13: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:14:33: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:14:33: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:14:38: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.180.228:27017, connect ENETUNREACH 64:ff9b::9f29:b4e4:27017 - Local (:::0)
2025-06-27T12:14:40: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:14:40: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:14:50: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:15:40: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:15:40: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:15:52: Bot error: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/sendMessage failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:15:53: Error in handleStart: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/sendMessage failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:16:08: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:16:08: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:16:18: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:90:21)
    at runNextTicks (node:internal/process/task_queues:69:3)
    at process.processTimers (node:internal/timers:520:9) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:233:35)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:16:39: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:16:39: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:16:50: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:16:51: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:17:01: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:17:31: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:17:32: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:17:42: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:17:51: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:17:51: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:18:02: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:19:05: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:26:56: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:26:57: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:27:03: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.180.228:27017, connect ENETUNREACH 64:ff9b::9f29:b4e4:27017 - Local (:::0)
2025-06-27T12:27:07: Error testing Telegram API connection: FetchError: request to https://api.telegram.org/bot8090075203:AAExEFee3sWbOcFkQwyrc8q6QDQLMnrxpMU/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:27:08: Error starting bot: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:27:18: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot8090075203:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:232:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:33:28: Error testing Telegram API connection: request to https://api.telegram.org/bot7358551906:AAH_7ucQtaizG3JAqVWt0ABrK2BszwaMbTY/getMe failed, reason: 
2025-06-27T12:33:28: Error starting bot: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:33:39: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:245:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:38:14: Error in handleTicketCallbacks: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleTicketCallbacks (/home/aditya/ctu/user-bot/controllers/ticketController.js:458:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: { text: undefined, callback_query_id: '4885528959418522828' }
  }
}
2025-06-27T12:38:15: Error in handleTicketCallbacks: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleTicketCallbacks (/home/aditya/ctu/user-bot/controllers/ticketController.js:458:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: { text: undefined, callback_query_id: '4885528961061412707' }
  }
}
2025-06-27T12:38:26: Error in handleTicketCallbacks: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleTicketCallbacks (/home/aditya/ctu/user-bot/controllers/ticketController.js:458:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: { text: undefined, callback_query_id: '4885528961927820555' }
  }
}
2025-06-27T12:38:56: Error in handleTicketCallbacks: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleTicketCallbacks (/home/aditya/ctu/user-bot/controllers/ticketController.js:458:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: { text: undefined, callback_query_id: '4885528961454782144' }
  }
}
2025-06-27T12:39:00: Error in handleTicketCallbacks: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleTicketCallbacks (/home/aditya/ctu/user-bot/controllers/ticketController.js:458:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: { text: undefined, callback_query_id: '4885528961727127552' }
  }
}
2025-06-27T12:40:10: Bot error: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/sendMessage failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-27T12:40:10: Error in handleTicketCallbacks: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleTicketCallbacks (/home/aditya/ctu/user-bot/controllers/ticketController.js:458:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: { text: undefined, callback_query_id: '4885528960575754763' }
  }
}
2025-06-27T12:42:02: Error in handleLanguageCallback: TelegramError: 400: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleLanguageCallback (/home/aditya/ctu/user-bot/controllers/userController.js:97:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message'
  },
  on: {
    method: 'editMessageText',
    payload: {
      chat_id: 5741696922,
      message_id: 44,
      inline_message_id: undefined,
      text: 'Language set to English.'
    }
  }
}
2025-06-27T12:42:44: Error testing Telegram API connection: request to https://api.telegram.org/bot7358551906:AAH_7ucQtaizG3JAqVWt0ABrK2BszwaMbTY/getMe failed, reason: 
2025-06-27T12:44:55: Error in handleTicketCallbacks: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleTicketCallbacks (/home/aditya/ctu/user-bot/controllers/ticketController.js:458:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: { text: undefined, callback_query_id: '6213656430811625432' }
  }
}
2025-06-27T12:44:55: Error in handleTicketCallbacks: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleTicketCallbacks (/home/aditya/ctu/user-bot/controllers/ticketController.js:458:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: { text: undefined, callback_query_id: '6213656434103034893' }
  }
}
2025-06-27T12:45:57: Bot error: TimeoutError: Promise timed out after 90000 milliseconds
    at Timeout._onTimeout (/home/aditya/ctu/user-bot/node_modules/p-timeout/index.js:39:64)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
2025-06-27T12:46:09: Error answering callback query: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/answerCallbackQuery failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketOnEnd (node:_http_client:542:5)
    at TLSSocket.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
2025-06-27T12:46:10: Error in handleLanguageCallback: TelegramError: 400: Bad Request: query is too old and response timeout expired or query ID is invalid
    at Telegram.callApi (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/core/network/client.js:315:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handleLanguageCallback (/home/aditya/ctu/user-bot/controllers/userController.js:96:5)
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17)
    at async /home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:519:21
    at async execute (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/composer.js:518:17) {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: query is too old and response timeout expired or query ID is invalid'
  },
  on: {
    method: 'answerCallbackQuery',
    payload: {
      text: 'Language set to English.',
      callback_query_id: '4885528961618371426'
    }
  }
}
2025-06-27T12:48:59: Error testing Telegram API connection: request to https://api.telegram.org/bot7358551906:AAH_7ucQtaizG3JAqVWt0ABrK2BszwaMbTY/getMe failed, reason: 
2025-06-27T12:49:46: Telegram API connection timeout
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:266:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:49:54: Error starting bot: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
Error: Bot is not running!
    at Telegraf.stop (/home/aditya/ctu/user-bot/node_modules/telegraf/lib/telegraf.js:218:19)
    at process.<anonymous> (/home/aditya/ctu/user-bot/app.js:266:34)
    at Object.onceWrapper (node:events:633:26)
    at process.emit (node:events:518:28)
2025-06-27T12:50:04: Error testing Telegram API connection: request to https://api.telegram.org/bot7358551906:AAH_7ucQtaizG3JAqVWt0ABrK2BszwaMbTY/getMe failed, reason: 
2025-06-27T12:50:33: Telegram API connection timeout
2025-06-27T12:52:22: Telegram API connection timeout
2025-06-27T12:52:38: Bot error: MongooseError: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/home/aditya/ctu/user-bot/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
2025-06-27T12:52:52: Error connecting to MongoDB Atlas: connection timed out
2025-06-27T12:53:28: Error connecting to MongoDB Atlas: Server selection timed out after 30000 ms
2025-06-27T12:53:42: Telegram API connection timeout
2025-06-27T13:17:19: Bot error: TimeoutError: Promise timed out after 90000 milliseconds
    at Timeout._onTimeout (/home/aditya/ctu/user-bot/node_modules/p-timeout/index.js:39:64)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/sendMessage failed, reason: getaddrinfo EAI_AGAIN api.telegram.org
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
2025-06-27T13:17:29: Unhandled Promise Rejection: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/sendMessage failed, reason: getaddrinfo EAI_AGAIN api.telegram.org
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
2025-06-27T13:17:30: Error in handleStart: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/sendMessage failed, reason: read ETIMEDOUT
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-29T00:29:42: Error testing Telegram API connection: request to https://api.telegram.org/bot7358551906:AAH_7ucQtaizG3JAqVWt0ABrK2BszwaMbTY/getMe failed, reason: 
2025-06-29T00:29:43: Error starting bot: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-29T00:29:44: Error connecting to MongoDB Atlas: connect ETIMEDOUT 159.41.233.33:27017, connect ENETUNREACH 64:ff9b::9f29:e921:27017 - Local (:::0)
2025-06-29T00:29:50: Error starting bot: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
2025-06-29T00:29:53: Failed to start bot on retry: FetchError: request to https://api.telegram.org/bot7358551906:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/aditya/ctu/user-bot/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
